add_library(Platform
    WinFileSystemProvider.cpp
    WinFileSystemProvider.h
    WinPathHelper.cpp
    WinPathHelper.h
    WinFileSystemWatcher.cpp
    WinFileSystemWatcher.h
    WinThumbnailProvider.cpp
    WinThumbnailProvider.h
    LLMClient.cpp
    LLMClient.h
    WinPlatformHooks.cpp
    IPlatformHooks.h
    GeminiLLMClient.cpp
    GeminiLLMClient.h
)

target_link_libraries(Platform
    PUBLIC
        Domain
    PRIVATE
        Qt6::Network
        Qt6::Core
)
